// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/6/2026, 12:54:20 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/plugins/**/*.{js,ts,mjs}","/app/app/composables/**/*.{js,ts,mjs}","/app/app/utils/**/*.{js,ts,mjs}","/app/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/app/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/app/app/app.config.{js,ts,mjs}"]}},
{"darkMode":["selector","[data-theme=\"dark\"]"],"theme":{"extend":{"fontFamily":{"sans":["Circular Std","sans-serif"],"defonte":["Defonte","serif"]},"keyframes":{"shimmer":{"0%":{"transform":"translateX(-100%)"},"50%, 100%":{"transform":"translateX(200%)"}},"spin-ring":{"0%, 100%":{"strokeDashoffset":"80"},"50%":{"strokeDashoffset":"200"}}},"animation":{"shimmer":"shimmer 3s ease-in-out infinite","spin-ring":"spin-ring 3s ease-in-out infinite"}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;